### ISSUE TITLE
跟著學習如何架 Hugo 

### ISSUE THREAD

**Issue by wastu01** [lin-snow/blog#1]
照著您的 deploy 腳本無法自動跑腳本
增加以下內容以及修改 hugo version 後成功運行

提供給其他人參考

```
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
```
